# -*- coding: utf-8 -*-
"""Solution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11dL4uQoezaz6lCwooVcpdGrkTNjZQxAt
"""



"""Python Program for Fibonacci numbers"""

# Function for nth fibonacci number - Space Optimisataion 
# Taking 1st two fibonacci numbers as 0 and 1 

def fibonacci(n): 
	a = 0
	b = 1
	if n < 0: 
		print("Incorrect input") 
	elif n == 0: 
		return a 
	elif n == 1: 
		return b 
	else: 
		for i in range(2,n): 
			c = a + b 
			a = b 
			b = c 
		return b 

# Driver Program 

print(fibonacci(9))

"""Python Program for Sum of first n natural numbers"""

# Python program to find the sum of natural numbers up to n where n is provided by user
# change this value for a different result
num = 16

# uncomment to take input from the user
#num = int(input("Enter a number: "))

if num < 0:
   print("Enter a positive number")
else:
   sum = 0
   # use while loop to iterate un till zero
   while(num > 0):
       sum += num
       num -= 1
   print("The sum is",sum)

"""Python Program for Program to find area of a Square"""

# Python3 code to find 
# the area of the square 

def areaSquare( side ): 
	area = side * side 
	return area 

# Driver Code 
side = 4
print(areaSquare(side))

"""Compound Interest"""

#Compound interest

#Compound Interest = P(1 + R/100)r
#Where,
#P is principle amount
#R is the rate and
#T is the time span

# Python3 program to find compound
# interest for given values.

def compound_interest(principle, rate, time):

	# Calculates compound interest
	CI = principle * (pow((1 + rate / 100), time))
	print("Compound interest is", CI)

# Driver Code
compound_interest(10000, 10.25, 5)

"""Simple Interest"""

# Python3 program to find simple interest
# for given principal amount, time and
# rate of interest.

# We can change values here for
# different inputs
P = 1
R = 1
T = 1

# Calculates simple interest
SI = (P * R * T) / 100

# Print the resultant value of SI
print("simple interest is", SI)

"""ASCII Number"""

# Python program to print
# ASCII Value of Character

# In c we can assign different
# characters of which we want ASCII value

c = 'o'
# print the ASCII value of assigned character in c
print("The ASCII value of '" + c + "' is", ord(c))