# -*- coding: utf-8 -*-
"""Week2-Sat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K308LOXOpepkc1_e-7xf7acEi8Im9HMw
"""

x = 2
y = 2
x=y

z =(x==y)
x=y
print (type(x))

"""Armstrong number"""

num = int(input("enter a number: "))

length = len(str(num))
sum = 0
temp = num

while (temp != 0):
    sum = sum + ((temp % 10) ** length)
    temp = temp // 10

if sum == num:
    print("armstrong number")
else:
    print("not armstrong number")

"""Prime Number"""

num = int(input("enter number of digits you want in series (minimum 2): "))
 
first = 0
second = 1
 
print("\nfibonacci series is:")
print(first, ",", second, end=", ")
 
for i in range(2, num):
	next = first + second
	print(next, end=", ")
 
	first = second
	second = next