# -*- coding: utf-8 -*-
"""week3 sat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QioL8u__vL8x1cJES6lIRPwEIUdQHjP4
"""

sum = 0
i = 0
num = int(input("kindly enter the positive number"))
while (i<=num):
  sum = sum+i
  i = i+1
  print(sum)

sum = 0
i = 0
num = int(input("kindly enter the positive number"))
for i in range(0, num+1):
  sum = sum+i
  print(sum)

x = 3
x*= 5
print(x)

x=5
y=5
sum=x+y
print(sum)
sub=x-y
print(sub)
product=x*y
print(product)
div=x/y
print(div)

""".) Given an integer, x perform the following conditional actions:

• If x is odd, print Weird

• If x is even and in the inclusive range of to , print Not Weird

• If x is even and in the inclusive range of to , print Weird

• If x is even and greater than , print Not Weird
"""

x = int(input(kindly enter number))
if x is odd
  print(weird)
  elif

"""1.) Write a python Program to Add ,Multiply, Divide & Substract two numbers."""

a = int(input("Kindly enter your number"))
b = input("choose operator")
c = int (input("kindly enter your second number"))
d = a+c, a-c, a*c

"""Function"""

def sum(a,b):
    c = a+b
    return (c)
sum(5,6)
sum(50,60)

"""def minus(a,b):
  c = a-b
  return (c)
minus (10,9)
"""

def minus(a,b):
  c = a-b
  return (c)
minus (10,9)

def mul(a,b):
  c = a*b
  return (c)
mul (5,4)

def mul(a,b):
  c = a%b
  return (c)
mul (5,4)

x = "january"
y = x.casefold()
print(y)

x = str(input("kindly enter month"))
y = x.capitalize()
print(y)

def m_d(y):
  if y == "January" or y == "March" or y == "May" or y == "July" or y =="December":
    print ("your selected month {} has 31 number of days".format(y))
  elif y == "February". format(y):
    print ("your month of {} is 28")
  elif y == "September" or y == "October" or y == "June". format(y):
    print ("your month of {} is 30 days")
  else:
    print ("not correct month {}")

m_d(y)

list = [0,1,2,3,4,5,6,7,8,9,10]
def check (list):
  for x in list:
    print (x)
    
check(x)