# -*- coding: utf-8 -*-
"""week4sun.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vjdP5uXfDmi3n65ePDqXGQ4U4TpScOii
"""

import random
x = random.randint(1,100)
print (x)
y = 0
z = str(input("please enter your name"))
for y in range(1,100):
  t = int(input("please choose your 1st number: "))
  if t >= 30:
    print ("C")
  else:
    print("sorry")

l = [1,1,2,3,4,4,5]
set(l)
for y in l:
  if y == 3:
    print("Amazing India")
  elif y == 5:
    print("incredible india")
  else:
    print("nice")

class home():
  land
  residential
  commercial
  area
  boundary
  water
  electricity
  walls
  door
  furntiure
  floor
  terrace
  gallery
  washrooms
  bedroom
  hall
  living room
  curtains
  interior
  wall colors
  lighting
  lawn
  windows
  terrace
  gate
  security
  garden
  shower
  bathtup
  comodetype
  petroom
  storageroom
  staircase
  kitchen
  tv
  roadconnectivity
  hospitalaccess
  spycameras
  pool
  gamingroom

"""function
1. non dependent
2. Input (arg, por, kprg)
3. syntax -def
4
5. for


---

Classess

1. Dependant
2. class input
3. class
"""

x = [1,2,3,4,5,6,7]
y = len(x)
print("length is", y)
n = sum(x)
print("sum is", n)
z = n/y
print("mean is", z)
w = (y+1)/2
print("media is", w)