# -*- coding: utf-8 -*-
"""Week4 Sat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ei7hivnUgCj9i8sdRSm5XfTddUmVmtMq
"""

x = 72
print (type(x))

"""Lenght"""

x = ["1", 1, "ram"]
len(x)

list2 = []
list1 = ["violet", "red", "green", "blue"]

for x in list1:
  if x[0] == "r":
    list2.append(x)
    
print(list2)

"""Dictionary"""

x = [[0,1], "ved",1,20,"jov",[0,1,"ved"]]
x[5][2]

x = [[0,1,2,3,4, "ved",[0,1,2]]], [1,2,["ved","shu","prat","jov"],5,7.0],[1,2,3,4,5,6,7,8,9,10],["ram",[1,0,[0,1,2],4]]
y = []
y.append(x[1])
print(y)

x = [[0,1,2,3,4, "ved",[0,1,2]]], [1,2,["ved","shu","prat","jov"],5,7.0],[1,2,3,4,5,6,7,8,9,10],["ram",[1,0,[0,1,2],4]]
y = []

for z in x:
  if z[0] == "s":
    y.append(z)

print(y)

x = {"ram":1, "laxman":2}
print (len(x))
print (type(x))
x["ram"]

x = {"nitin":[{"ec":4321, "dob":1419991, "gender":"male"}]}
x["nitin"][0]["gender"]

x = {"ram":[{"ec":4321, "dob":1419991, "gender":"male"}], "laxman":[{"ec":54, "dob":1819997, "gender":"male"}], "charan":[{"ec":78, "dob":1619996, "gender":"female" }]}
print(len(x))
y = str(input("kindly enter your name"))
z = str(input("what you want to know, ec, dob, gender"))
x[y][0][z]

colours = {"vedant": "pink", "jovin": "skyblue", "Nitin": "green", "ishika": "purple", "komal": "navyblue", "deep": "oxford blue"}
colours["pratiksha"] = "red"
colours["mayur"] = "pink"
print(colours)

x = {"ram":[{"ec":4321, "dob":1419991, "gender":"male"}], "laxman":[{"ec":54, "dob":1819997, "gender":"male"}], "charan":[{"ec":78, "dob":1619996, "gender":"female" }]}
x["ravan"]= [{"ec":4321, "dob":1419991, "gender":"male"}]
print(x)
y = str(input("kindly enter your name"))
z = str(input("your dob"))
d = str(input("your gender"))
p = str(input("your Empid"))
x[y] = [{"Empid":p ,"DOB":z ,"Gender":d }]
print(x)

"""learn 4 types of system error

Choose number game
"""

import random
x = random.randint(1,100)
print (x)
y = 0
z = str(input("please enter your name"))
for y in range(1,100):
  t = int(input("please choose your 1st number: "))
  if t >= 30:
    print ("C")
  else:
    print("sorry")

class Topwear():
  gender
  toptype
  material
  size
  sleeves
  prints
  necktype
  buttons
  shirt
  tshirt
  hoodies
  zipper
  collar
  length
  color
  stretch
  pockets
  wash
  brand
  party
  formal
  informal
  casual
  kurta

class home():
  land
  residential
  commercial
  area
  boundary
  water
  electricity
  walls
  door
  furntiure
  floor
  terrace
  gallery
  washrooms
  bedroom
  hall
  living room
  curtains
  interior
  wall colors
  lighting
  lawn
  windows
  terrace
  gate
  security
  garden
  shower
  bathtup
  comodetype
  petroom
  storageroom
  staircase
  kitchen
  tv
  roadconnectivity
  hospitalaccess

"""function"""