# -*- coding: utf-8 -*-
"""week 1 sat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GreR7M1gaT0hSLkNZIsCusf8JT7rDdUc
"""

print ("Hello world")

a = int (input ("Kindly enter 1st number"))
b =int(input ("kindly enter 2nd number"))
d = str (input ("kindly enter 3rd number"))
c = a+b

print ("addition of two number is",c)
print ("addition of two number is",c)

a = int (input ("kindly enter the integer"))
b = int (input ("kindly enter the number")) 
c= (a+b)/(a-b)

print (addition of first two numbers)

a= int (input ("kindly enter the integer"))
b= float (input ("kindly enter the float"))
c= str (input("kindly enter the string"))
d= a>b

print ("a is {}, b is {}, c is {} and value of d is {}". format (a,b,c,d))

a = int (input ("Kindly enter 1st number"))
b =int(input ("kindly enter 2nd number"))

c = a+b
d = a-b
e = a*b
f = a/b

print ("addition of two number is",c)
print ("product of two number is",d)